### ISSUE TITLE
连接cn-proxy.com超时

### ISSUE THREAD

**Issue by ekkkkki** [yi-ji/NeteaseMusicAbroad#51]
网易云版本：1.5.0
启动无效。错误日志如下，看起来是连接cn-proxy时候出了问题。
```
python NeteaseMusicProxy.py
/Users/eric/Library/CloudStorage/OneDrive-Personal/Program/NeteaseMusicAbroad/NeteaseMusicProxy.py:4: DeprecationWarning: twisted.python.compat.urllib_parse was deprecated in Twisted 21.2.0: Import urllib.parse directly
  from twisted.python.compat import urllib_parse
2024-05-29 22:50:55+0900 [-] Log opened.
2024-05-29 22:52:10+0900 [-] Traceback (most recent call last):
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
2024-05-29 22:52:10+0900 [-]     sock = connection.create_connection(
2024-05-29 22:52:10+0900 [-]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
2024-05-29 22:52:10+0900 [-]     raise err
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
2024-05-29 22:52:10+0900 [-]     sock.connect(sa)
2024-05-29 22:52:10+0900 [-] TimeoutError: [Errno 60] Operation timed out
2024-05-29 22:52:10+0900 [-]
2024-05-29 22:52:10+0900 [-] The above exception was the direct cause of the following exception:
2024-05-29 22:52:10+0900 [-]
2024-05-29 22:52:10+0900 [-] Traceback (most recent call last):
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
2024-05-29 22:52:10+0900 [-]     response = self._make_request(
2024-05-29 22:52:10+0900 [-]                ^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
2024-05-29 22:52:10+0900 [-]     conn.request(
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
2024-05-29 22:52:10+0900 [-]     self.endheaders()
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/http/client.py", line 1281, in endheaders
2024-05-29 22:52:10+0900 [-]     self._send_output(message_body, encode_chunked=encode_chunked)
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/http/client.py", line 1041, in _send_output
2024-05-29 22:52:10+0900 [-]     self.send(msg)
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/http/client.py", line 979, in send
2024-05-29 22:52:10+0900 [-]     self.connect()
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
2024-05-29 22:52:10+0900 [-]     self.sock = self._new_conn()
2024-05-29 22:52:10+0900 [-]                 ^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
2024-05-29 22:52:10+0900 [-]     raise ConnectTimeoutError(
2024-05-29 22:52:10+0900 [-] urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x106763fd0>, 'Connection to cn-proxy.com timed out. (connect timeout=None)')
2024-05-29 22:52:10+0900 [-]
2024-05-29 22:52:10+0900 [-] The above exception was the direct cause of the following exception:
2024-05-29 22:52:10+0900 [-]
2024-05-29 22:52:10+0900 [-] Traceback (most recent call last):
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-05-29 22:52:10+0900 [-]     resp = conn.urlopen(
2024-05-29 22:52:10+0900 [-]            ^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2024-05-29 22:52:10+0900 [-]     retries = retries.increment(
2024-05-29 22:52:10+0900 [-]               ^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-05-29 22:52:10+0900 [-]     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-05-29 22:52:10+0900 [-]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-] urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='cn-proxy.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x106763fd0>, 'Connection to cn-proxy.com timed out. (connect timeout=None)'))
2024-05-29 22:52:10+0900 [-]
2024-05-29 22:52:10+0900 [-] During handling of the above exception, another exception occurred:
2024-05-29 22:52:10+0900 [-]
2024-05-29 22:52:10+0900 [-] Traceback (most recent call last):
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/Library/CloudStorage/OneDrive-Personal/Program/NeteaseMusicAbroad/NeteaseMusicProxy.py", line 266, in <module>
2024-05-29 22:52:10+0900 [-]     mainland_proxy = MainlandProxy()
2024-05-29 22:52:10+0900 [-]                      ^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/Library/CloudStorage/OneDrive-Personal/Program/NeteaseMusicAbroad/NeteaseMusicProxy.py", line 64, in __init__
2024-05-29 22:52:10+0900 [-]     self.set_proxy()
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/Library/CloudStorage/OneDrive-Personal/Program/NeteaseMusicAbroad/NeteaseMusicProxy.py", line 69, in set_proxy
2024-05-29 22:52:10+0900 [-]     r = requests.get("http://cn-proxy.com/")
2024-05-29 22:52:10+0900 [-]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/requests/api.py", line 73, in get
2024-05-29 22:52:10+0900 [-]     return request("get", url, params=params, **kwargs)
2024-05-29 22:52:10+0900 [-]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/requests/api.py", line 59, in request
2024-05-29 22:52:10+0900 [-]     return session.request(method=method, url=url, **kwargs)
2024-05-29 22:52:10+0900 [-]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-05-29 22:52:10+0900 [-]     resp = self.send(prep, **send_kwargs)
2024-05-29 22:52:10+0900 [-]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-05-29 22:52:10+0900 [-]     r = adapter.send(request, **kwargs)
2024-05-29 22:52:10+0900 [-]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-29 22:52:10+0900 [-]   File "/Users/eric/.pyenv/versions/3.11.6/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
2024-05-29 22:52:10+0900 [-]     raise ConnectTimeout(e, request=request)
2024-05-29 22:52:10+0900 [-] requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='cn-proxy.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x106763fd0>, 'Connection to cn-proxy.com timed out. (connect timeout=None)'))
```

**Comment by yi-ji** [comment]
试一下能否浏览器打开 http://cn-proxy.com/
