### ISSUE TITLE
环境都应该安装好了然后运行helper显示all set但是打开网易云还是灰的？

### ISSUE THREAD

**Issue by wzjin2017** [yi-ji/NeteaseMusicAbroad#8]
另外，All set上面有这样的信息

> ~/Users//Desktop/NeteaseMusicAbroad-master/NeteaseMusicHelper ; exit;
find: /Users///Library/Saved Application State/com.solidstatenetworks.host.savedState: Permission denied

**Comment by yi-ji** [comment]
麻烦手动执行一下 python NeteaseMusicProxy.py 看一下输出？

**Comment by wzjin2017** [comment]
Output返回是
`2018-09-03 08:52:26-0400 [-] Log opened.
2018-09-03 08:52:26-0400 [-] Traceback (most recent call last):
2018-09-03 08:52:26-0400 [-]   File "NeteaseMusicProxy.py", line 225, in <module>
2018-09-03 08:52:26-0400 [-]     reactor.listenTCP(32794, NeteaseMusicProxyFactory())
2018-09-03 08:52:26-0400 [-]   File "/Library/Python/2.7/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2018-09-03 08:52:26-0400 [-]     p.startListening()
2018-09-03 08:52:26-0400 [-]   File "/Library/Python/2.7/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2018-09-03 08:52:26-0400 [-]     raise CannotListenError(self.interface, self.port, le)
2018-09-03 08:52:26-0400 [-] twisted.internet.error.CannotListenError: Couldn't listen on any:32794: [Errno 48] Address already in use.`

**Comment by wzjin2017** [comment]
返回结果是

> 2018-09-03 08:52:26-0400 [-] Log opened.
2018-09-03 08:52:26-0400 [-] Traceback (most recent call last):
2018-09-03 08:52:26-0400 [-]   File "NeteaseMusicProxy.py", line 225, in <module>
2018-09-03 08:52:26-0400 [-]     reactor.listenTCP(32794, NeteaseMusicProxyFactory())
2018-09-03 08:52:26-0400 [-]   File "/Library/Python/2.7/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2018-09-03 08:52:26-0400 [-]     p.startListening()
2018-09-03 08:52:26-0400 [-]   File "/Library/Python/2.7/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2018-09-03 08:52:26-0400 [-]     raise CannotListenError(self.interface, self.port, le)
2018-09-03 08:52:26-0400 [-] twisted.internet.error.CannotListenError: Couldn't listen on any:32794: [Errno 48] Address already in use.

**Comment by yi-ji** [comment]
端口32794被占说明你之前helper的进程还没退出，把它kill掉再试一下。不会kill的话关掉网易云重启mac也行

为了确认一下不是别的进程占了32794端口，执行一下`sudo lsof -i :32794`看看

**Comment by wzjin2017** [comment]
解决了问题 感谢！
